### ISSUE TITLE
<a href="javascript:alert(55)">Clickon</a>

### ISSUE THREAD

**Issue by ashketchum1410** [ash/books#1]
<a href="javascript:alert(55)">Clickon</a>

**Comment by ashketchum12165** [comment]
<a href="javascript:alert(55)">Clickon</a>[](url)

**Comment by ashketchum12165** [comment]
> Clickon

MDEyOklzc3VlQ29tbWVudDYxMDU4MzQ3OA==

**Comment by ashketchum12165** [comment]
> > Clickon
> <a href="javascript:alert(55)">Clickon</a>
> MDEyOklzc3VlQ29tbWVudDYxMDU4MzQ3OA==

**Comment by ashketchum12165** [comment]
<a href="javascript:alert(55)">Clickon</a>

**Comment by ashketchum12165** [comment]
> <a href="javascript:alert(55)">Clickon</a>
